-- MySQL Script generated by MySQL Workbench
-- jue 07 nov 2019 09:58:31 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS "mydb";
-- USE "mydb" ;

-- -----------------------------------------------------
-- Table "mydb"."CLIENTE"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "mydb"."CLIENTE" (
  "dni" VARCHAR(9) NOT NULL,
  "bonificacion" DECIMAL(2),
  "totalMensual" DECIMAL(2),
  PRIMARY KEY ("dni"));




-- -----------------------------------------------------
-- Table "mydb"."PRODUCTO"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "mydb"."PRODUCTO" (
  "codigoProducto" INT NOT NULL,
  "stock" INT,
  "precio" DECIMAL(2) NULL,
  PRIMARY KEY ("codigoProducto"));


-- -----------------------------------------------------
-- Table "mydb"."EMPLEADO"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "mydb"."EMPLEADO" (
  "dni" VARCHAR(9) NOT NULL,
  "sueldo" DECIMAL(2) NOT NULL,
  "css" INT NULL,
  "antigüedad" DATE NOT NULL,
  PRIMARY KEY ("dni"));


-- -----------------------------------------------------
-- Table "mydb"."VENTAS"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "mydb"."VENTAS" (
  "cantidad" INT NULL,
  "codigoProducto" INT NOT NULL,
  "dni_cliente" VARCHAR(9) NULL,
  "dni_empleado" VARCHAR(9) NULL,
  "anio" INT NOT NULL,
  "mes" INT NOT NULL,
  "dia" INT NOT NULL,
  "hora" INT NOT NULL,
  "minuto" INT NOT NULL,
  "segundo" INT NOT NULL,
  PRIMARY KEY ("codigoProducto", "anio", "mes", "dia", "hora", "minuto", "segundo"),
  CONSTRAINT "codigoProducto"
    FOREIGN KEY ("codigoProducto")
    REFERENCES "mydb"."PRODUCTO" ("codigoProducto")
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT "dni_cliente"
    FOREIGN KEY ("dni_cliente")
    REFERENCES "mydb"."CLIENTE" ("dni")
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT "dni_empleado" 
    FOREIGN KEY ("dni_empleado")
    REFERENCES "mydb"."EMPLEADO" ("dni")
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table "mydb"."VIVERO"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "mydb"."VIVERO" (
  "coordenadas" VARCHAR(45) NOT NULL,
  "localidad" VARCHAR(45) NULL,
  PRIMARY KEY ("coordenadas"));



-- -----------------------------------------------------
-- Table "mydb"."ZONA"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "mydb"."ZONA" (
  "nombre" VARCHAR(20) NOT NULL,
  "coordenadas" VARCHAR(45) NOT NULL,
  "dni_empleado" VARCHAR(9) NULL,
  "anio_ini" INT NOT NULL,
  "anio_fin" INT NULL,
  "mes_ini" INT NOT NULL,
  "mes_fin" INT NULL,
  "dia_ini" INT NOT NULL,
  "dia_fin" INT NULL,
  "hora_ini" INT NOT NULL,
  "hora_fin" INT NULL,
  "minuto_ini" INT NOT NULL,
  "minuto_fin" INT NULL,
  "segundo_ini" INT NOT NULL,
  "segundo_fin" INT NULL,
  "ventas" INT,
  PRIMARY KEY ("nombre", "coordenadas", "anio_ini", "mes_ini", "dia_ini", "hora_ini", "minuto_ini", "segundo_ini"),
  CONSTRAINT "dni_empleado"
    FOREIGN KEY ("dni_empleado")
    REFERENCES "mydb"."EMPLEADO" ("dni")
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT "coordenadas"
    FOREIGN KEY ("coordenadas")
    REFERENCES "mydb"."VIVERO" ("coordenadas")
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table "mydb"."PRODUCTO_has_ZONA"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "mydb"."ZONA_has_PRODUCTO" (
  "ZONA_nombre" VARCHAR(20) NOT NULL,
  "ZONA_coordenadas" VARCHAR(45) NOT NULL,
  "ZONA_anio_ini" INT NOT NULL,
  "ZONA_mes_ini" INT NOT NULL,
  "ZONA_dia_ini" INT NOT NULL,
  "ZONA_hora_ini" INT NOT NULL,
  "ZONA_minuto_ini" INT NOT NULL,
  "ZONA_segundo_ini" INT NOT NULL,
  "PRODUCTO_codigoProducto" INT  NOT NULL,
  PRIMARY KEY ("ZONA_nombre", "ZONA_coordenadas", "ZONA_anio_ini", "ZONA_mes_ini", "ZONA_dia_ini", "ZONA_hora_ini", "ZONA_minuto_ini", "ZONA_segundo_ini", "PRODUCTO_codigoProducto"),
  CONSTRAINT "fk_ZONA_has_PRODUCTO_ZONA1"
    FOREIGN KEY ("ZONA_nombre" , "ZONA_coordenadas" , "ZONA_anio_ini" , "ZONA_mes_ini" , "ZONA_dia_ini" , "ZONA_hora_ini" , "ZONA_minuto_ini" , "ZONA_segundo_ini")
    REFERENCES "mydb"."ZONA" ("nombre" , "coordenadas" , "anio_ini" , "mes_ini" , "dia_ini" , "hora_ini" , "minuto_ini" , "segundo_ini")
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT "fk_ZONA_has_PRODUCTO_PRODUCTO1"
    FOREIGN KEY ("PRODUCTO_codigoProducto")
    REFERENCES "mydb"."PRODUCTO" ("codigoProducto")
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

