-- MySQL Script generated by MySQL Workbench
-- Mon Nov 11 19:57:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS "mydbFarmacia";

-- -----------------------------------------------------
-- Table "mydbFarmacia"."FAMILIA"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "mydbFarmacia"."FAMILIA" (
  "nombre" VARCHAR(20) NOT NULL,
  "incompatibilidades" VARCHAR(100) NULL,
  PRIMARY KEY ("nombre"))
;


-- -----------------------------------------------------
-- Table "mydbFarmacia"."ENFERMEDAD"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "mydbFarmacia"."ENFERMEDAD" (
  "nombre" VARCHAR(20) NOT NULL,
  "sintoma" VARCHAR(100) NULL,
  PRIMARY KEY ("nombre"))
;


-- -----------------------------------------------------
-- Table "mydbFarmacia"."FAMILIA_ENFERMEDAD"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "mydbFarmacia"."FAMILIA_ENFERMEDAD" (
  "nombre_enfermedad" VARCHAR(20) NOT NULL,
  "nombre_familia" VARCHAR(20) NOT NULL,
  PRIMARY KEY ("nombre_enfermedad", "nombre_familia"),
  CONSTRAINT "nombre_familia"
    FOREIGN KEY ("nombre_familia")
    REFERENCES "mydbFarmacia"."FAMILIA" ("nombre")
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT "nombre_enfermedad"
    FOREIGN KEY ("nombre_enfermedad")
    REFERENCES "mydbFarmacia"."ENFERMEDAD" ("nombre")
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table "mydbFarmacia"."LABORATORIO"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "mydbFarmacia"."LABORATORIO" (
  "codigo_lab" INT NOT NULL,
  "contacto" VARCHAR(45) NULL,
  "calle" VARCHAR(45) NULL,
  "numero" INT NULL,
  "cp" INT NULL,
  "nombre" VARCHAR(45) NULL,
  "telefono" VARCHAR(45) NULL,
  PRIMARY KEY ("codigo_lab"))
;


-- -----------------------------------------------------
-- Table "mydbFarmacia"."MEDICAMENTOS"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "mydbFarmacia"."MEDICAMENTOS" (
  "codigo" INT NOT NULL,
  "nombre" VARCHAR(45) NULL,
  "posologia" VARCHAR(45) NULL,
  "igic" DECIMAL NULL,
  "precio" DECIMAL NULL,
  "tipo" VARCHAR(45) NOT NULL,
  "laboratorio" INT NULL,
  PRIMARY KEY ("codigo"),
  CONSTRAINT "laboratorio"
    FOREIGN KEY ("laboratorio")
    REFERENCES "mydbFarmacia"."LABORATORIO" ("codigo_lab")
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table "mydbFarmacia"."MEDICAMENTOS_FAMILIA"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "mydbFarmacia"."MEDICAMENTOS_FAMILIA" (
  "codigo_med" INT NOT NULL,
  "nombre_familia" VARCHAR(45) NOT NULL,
  PRIMARY KEY ("codigo_med", "nombre_familia"),
  CONSTRAINT "cod_medicamento"
    FOREIGN KEY ("codigo_med")
    REFERENCES "mydbFarmacia"."MEDICAMENTOS" ("codigo")
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT "nombre_familia"
    FOREIGN KEY ("nombre_familia")
    REFERENCES "mydbFarmacia"."FAMILIA" ("nombre")
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table "mydbFarmacia"."COMPRA"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "mydbFarmacia"."COMPRA" (
  "anio" INT NOT NULL,
  "mes" INT NOT NULL,
  "dia" INT NOT NULL,
  "hora" INT NOT NULL,
  "minuto" INT NOT NULL,
  "segundo" INT NOT NULL,
  "importe" DECIMAL NULL,
  PRIMARY KEY ("anio", "mes", "dia", "hora", "minuto", "segundo"))
;


-- -----------------------------------------------------
-- Table "mydbFarmacia"."COMPRA_MEDICAMENTOS"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "mydbFarmacia"."COMPRA_MEDICAMENTOS" (
  "COMPRA_anio" INT NOT NULL,
  "COMPRA_mes" INT NOT NULL,
  "COMPRA_dia" INT NOT NULL,
  "COMPRA_hora" INT NOT NULL,
  "COMPRA_minuto" INT NOT NULL,
  "COMPRA_segundo" INT NOT NULL,
  "MEDICAMENTOS_codigo" INT NOT NULL,
  "unidades" INT NULL,
  "igic" DECIMAL NULL,
  "importe_linea" DECIMAL NULL,
  PRIMARY KEY ("COMPRA_anio", "COMPRA_mes", "COMPRA_dia", "COMPRA_hora", "COMPRA_minuto", "COMPRA_segundo", "MEDICAMENTOS_codigo"),
  CONSTRAINT "fk_COMPRA_has_MEDICAMENTOS_COMPRA1"
    FOREIGN KEY ("COMPRA_anio" , "COMPRA_mes" , "COMPRA_dia" , "COMPRA_hora" , "COMPRA_minuto" , "COMPRA_segundo")
    REFERENCES "mydbFarmacia"."COMPRA" ("anio" , "mes" , "dia" , "hora" , "minuto" , "segundo")
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT "fk_COMPRA_has_MEDICAMENTOS_MEDICAMENTOS1"
    FOREIGN KEY ("MEDICAMENTOS_codigo")
    REFERENCES "mydbFarmacia"."MEDICAMENTOS" ("codigo")
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table "mydbFarmacia"."CLIENTE"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "mydbFarmacia"."CLIENTE" (
  "cc" VARCHAR(20) NOT NULL,
  "nombre" VARCHAR(45) NULL,
  "dia_pagos" INT NULL,
  PRIMARY KEY ("cc"))
;


-- -----------------------------------------------------
-- Table "mydbFarmacia"."PAGO_CREDITO"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "mydbFarmacia"."PAGO_CREDITO" (
  "anio" INT NOT NULL,
  "mes" INT NOT NULL,
  "cliente" VARCHAR(20) NOT NULL,
  "COMPRA_anio" INT NOT NULL,
  "COMPRA_mes" INT NOT NULL,
  "COMPRA_dia" INT NOT NULL,
  "COMPRA_hora" INT NOT NULL,
  "COMPRA_minuto" INT NOT NULL,
  "COMPRA_segundo" INT NOT NULL,
  "dia" INT NULL,
  "hora" INT NULL,
  "minuto" INT NULL,
  "segundo" INT NULL,
  "cant_abonada" DECIMAL NULL,
  PRIMARY KEY ("anio", "mes", "cliente", "COMPRA_anio", "COMPRA_mes", "COMPRA_dia", "COMPRA_hora", "COMPRA_minuto", "COMPRA_segundo"),
  CONSTRAINT "fecha_compra"
    FOREIGN KEY ("COMPRA_anio" , "COMPRA_mes" , "COMPRA_dia" , "COMPRA_hora" , "COMPRA_minuto" , "COMPRA_segundo")
    REFERENCES "mydbFarmacia"."COMPRA" ("anio" , "mes" , "dia" , "hora" , "minuto" , "segundo")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "cliente"
    FOREIGN KEY ("cliente")
    REFERENCES "mydbFarmacia"."CLIENTE" ("cc")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;
